name: Luogu
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *
jobs:
  update_luogu_punch:
    name: 更新洛谷每日打卡
    runs-on: ubuntu-latest
    permissions:
        actions: write
    steps:
        - name: 克隆仓库 (bitsstdcheee/code-backup)
          uses: actions/checkout@v3
          with:
              repository: bitsstdcheee/code-backup
              ref: development
              path: code
              token: ${{ secrets.REPO_KEY }}
              fetch-depth: 1
        - name: 克隆仓库 (bitsstdcheee/code-backup-status)
          uses: actions/checkout@v3
          with:
              repository: bitsstdcheee/code-backup-status
              ref: main
              path: status
              token: ${{ secrets.REPO_KEY }}
              fetch-depth: 1
        - name: 运行洛谷打卡
          run: |
            cp ./code/Luogu/cookie.txt ./status/luogu/cookie.txt
            ls ./status/luogu
            python ./status/luogu/punch.py file
        - run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/bitsstdcheee/code-backup-status/actions/workflows/58944712/dispatches \
            -d '{"ref":"main"}'
        # https://api.github.com/repos/bitsstdcheee/code-backup-status/actions/workflows
        # 59194359: labeler
        # 60946645: luogu
        # 60184206: mirror
        # 58944712: runner
        # -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'