name: Luogu
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 */2 * * *
jobs:
  update_luogu_punch:
    name: 更新洛谷每日打卡
    runs-on: ubuntu-latest
    steps:
        - run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <YOUR-TOKEN>"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bitsstdcheee/code-backup-status/actions/workflows/runner/dispatches \
            -d '{"ref":"main"}'
        # -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'