name: Luogu
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *
jobs:
  update_luogu_punch:
    name: 更新洛谷每日打卡
    runs-on: ubuntu-latest
    permissions:
        actions: write
    steps:
        - name: 克隆仓库 (bitsstdcheee/code-backup)
          uses: actions/checkout@v3
          with:
              repository: bitsstdcheee/code-backup
              ref: development
              path: code
              token: ${{ secrets.REPO_KEY }}
        - name: 克隆仓库 (bitsstdcheee/code-backup-status)
          uses: actions/checkout@v3
          with:
              repository: bitsstdcheee/code-backup-status
              ref: main
              path: status
              token: ${{ secrets.REPO_KEY }}
              fetch-depth: 1
        - name: 安装 bs4
          run: |
            sudo pip3 install Beautifulsoup4 
        - name: 运行洛谷打卡
          id: punch
          run: |
            cp ./code/Luogu/cookie.txt ./status/luogu/cookie.txt
            cp ./code/lucky.txt ./status/luogu/lucky.txt
            ls ./status/luogu
            cd ./status/luogu
            python time.py >> $GITHUB_STEP_SUMMARY
            python punch.py file || result=$?
            if [[ "$result" == '2' ]];then
              echo "用户未登录"
              echo "status=2" >> $GITHUB_OUTPUT
              echo "**错误**: 用户未登录" >> $GITHUB_STEP_SUMMARY
              exit 2
            elif [[ "$result" == '0' ]];then
              echo "status=0" >> $GITHUB_OUTPUT
              echo "打卡成功"
              echo "**成功**: 本次打卡成功" >> $GITHUB_STEP_SUMMARY
              echo "今日运势: " >> $GITHUB_STEP_SUMMARY
              cat summary.txt >> $GITHUB_STEP_SUMMARY
              exit 0
            elif [[ "$result" == '1' ]];then
              echo "status=1" >> $GITHUB_OUTPUT
              echo "用户已打卡"
              echo "**信息**: 用户今日已打卡" >> $GITHUB_STEP_SUMMARY
              exit 0
            elif [[ "$result" == '3' ]];then
              echo "未知错误"
              echo "**错误**: 未知错误 (code: 3)" >> $GITHUB_STEP_SUMMARY
              exit 3
            elif [[ "$result" == '4' ]];then
              echo "未知错误"
              echo "**错误**: 未知错误 (code: 4)" >> $GITHUB_STEP_SUMMARY
              exit 4
            else
              echo "未知错误"
              echo "**错误**: 未知错误" >> $GITHUB_STEP_SUMMARY
              exit 3
            fi
        - name: 添加更改
          run: |
            cp -rf ./status/luogu/lucky.txt ./code/lucky.txt
            cd ./code/
            git status
            git add .
        - name: 提交更改
          uses: bitsstdcheee/action-push@v1.4.1
          with:
              github_token: ${{ secrets.REPO_KEY }}
              message: "Update lucky (bot)"
              branch: "development"
              directory: ./code/
        - name: 上传构件
          uses: actions/upload-artifact@v3
          with:
            name: punch-file
            path: |
              ./status/luogu

            
        # https://api.github.com/repos/bitsstdcheee/code-backup-status/actions/workflows
        # 59194359: labeler
        # 60946645: luogu
        # 60184206: mirror
        # 58944712: runner
        # -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'