name: Luogu
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *
jobs:
  update_luogu_punch:
    name: 更新洛谷每日打卡
    runs-on: ubuntu-latest
    steps:
        - run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bitsstdcheee/code-backup-status/actions/workflows/58944712/dispatches \
            -d '{"ref":"main"}'
        # https://api.github.com/repos/bitsstdcheee/code-backup-status/actions/workflows
        # 59194359: labeler
        # 60946645: luogu
        # 60184206: mirror
        # 58944712: runner
        # -H "Authorization: Bearer <YOUR-TOKEN>"\
        # -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'