name: Mirror
concurrency:
  group: mirror
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      depth:
        description: 'Gitee 克隆深度'
        required: true
        type: number
  push:
    paths:
      - '.github/workflows/mirror.yml'
jobs:
  update_status:
    name: 更新代码状态
      # secrets:
      # status-token: ${{ github.REPO_KEY }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 克隆仓库 (github/bitsstdcheee/code-backup)
        id: clone-first
        uses: actions/checkout@v3
        with:
          repository: bitsstdcheee/code-backup
          ref: development
          path: code-backup-github
            # token: ${{ secrets.status-token }}
          token: ${{ secrets.REPO_KEY }}
      - name: 检查同步步骤状态
        id: sync-check
        if: ${{ steps.clone-first.conclusion == 'success' }}
        run: |
          echo "成功执行步骤"
      - name: 同步仓库 (Github -> Gitee)
        if: ${{ steps.sync-check.conclusion == 'success' }}
        id: sync-first
        run: |
          echo "::add-mask::${{ secrets.GITEE }}"
          echo "::add-mask::${{ secrets.REPO_KEY }}"
          cd code-backup-github
          git remote add gitee https://bitsstdcheee:${{ secrets.GITEE }}@gitee.com/bitsstdcheee/code-backup
          result=0
          git push gitee development --no-verify || result=1
          echo "结果:$result"
          echo "result=$result" >> "$GITHUB_OUTPUT"
          exit 0
      - name: 获取输入参数
        if: ${{ always() }}
        id: para-getter
        shell: bash
        run: |
          echo "输入克隆深度: ${{ inputs.depth }}"
          if [ -z "${{ inputs.depth }}" ] || [ ${{ inputs.depth }} -le 0 ]; then
            echo "克隆深度未设置 / 不合法, 将全量克隆"
            echo "depth=-1" >> "$GITHUB_OUTPUT"
          else
            echo "克隆深度设置为 ${{ inputs.depth }}"
            echo "depth=${{ inputs.depth }}" >> "$GITHUB_OUTPUT"
          fi
      - name: 克隆仓库 (gitee/bitsstdcheee/code-backup)
        if: ${{ steps.sync-check.conclusion == 'success' && (failure() || steps.sync-first.outputs.result != 0) }}
        id: clone-second
        run: |
          echo "::add-mask::${{ secrets.GITEE }}"
          echo "::add-mask::${{ secrets.REPO_KEY }}"
          if [ "${{ steps.para-getter.outputs.depth }}" -eq -1 ]; then
            git clone https://bitsstdcheee:${{ secrets.GITEE }}@gitee.com/bitsstdcheee/code-backup code-backup-gitee --progress
          else
            git clone https://bitsstdcheee:${{ secrets.GITEE }}@gitee.com/bitsstdcheee/code-backup code-backup-gitee --progress --depth=${{ steps.para-getter.outputs.depth }}
          fi
        shell: bash
      - name: 同步仓库 (Gitee -> Github)
        id: sync-second
        if: ${{ steps.sync-check.conclusion == 'success' && steps.clone-second.conclusion == 'success' && (failure() || steps.sync-first.outputs.result != 0) }}
        run: |
          echo "::add-mask::${{ secrets.GITEE }}"
          echo "::add-mask::${{ secrets.REPO_KEY }}"
          cd code-backup-gitee
          git remote add github https://bitsstdcheee:${{ secrets.REPO_KEY }}@github.com/bitsstdcheee/code-backup
          result=0
          git push github development --no-verify || result=1
          echo "结果:$result"
          echo "result=$result" >> "$GITHUB_OUTPUT"
      - name: 尝试 Auto Merge (基底 Gitee)
        if: ${{ steps.sync-check.conclusion == 'success' && (failure() || steps.sync-second.outputs.result != 0) }}
        run: |
          echo "::add-mask::${{ secrets.GITEE }}"
          echo "::add-mask::${{ secrets.REPO_KEY }}"
          cd code-backup-gitee
          git remote add gitee https://bitsstdcheee:${{ secrets.GITEE }}@gitee.com/bitsstdcheee/code-backup
          git config --global --add pull.rebase false
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch github development:github-mirror
          git merge github-mirror --commit -m "Auto Merge from Github"
          git push github development:development
          git push gitee development:development
