name: Mirror
on:
  workflow_dispatch:
jobs:
  update_status:
    name: 更新代码状态
      # secrets:
      # status-token: ${{ github.REPO_KEY }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 克隆仓库 (github/bitsstdcheee/code-backup)
        uses: actions/checkout@v3
        with:
          repository: bitsstdcheee/code-backup
          ref: development
          path: code-backup-github
            # token: ${{ secrets.status-token }}
          token: ${{ secrets.REPO_KEY }}
      - name: 克隆仓库 (gitee/bitsstdcheee/code-backup)
        run: |
          git clone https://bitsstdcheee:${{ secrets.GITEE }}@gitee.com/bitsstdcheee/code-backup code-backup-gitee
      - name: 同步仓库 (Github -> Gitee)
        id: sync-first
        run: |
          cd code-backup-github
          git remote add gitee https://bitsstdcheee:${{ secrets.GITEE }}@gitee.com/bitsstdcheee/code-backup
          git push gitee development --no-verify
      - name: 同步仓库 (Gitee -> Github)
        if: ${{ failure() }}
        run: |
          cd code-backup-gitee
          git remote add github https://bitsstdcheee:${{ secrets.REPO_KEY }}@github.com/bitsstdcheee/code-backup
          git push github development --no-verify
