name: Runner
on:
  push:
  workflow_dispatch:
jobs:
  update_status:
    name: 更新代码状态
      # secrets:
      # status-token: ${{ github.REPO_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库 (bitsstdcheee/code-backup)
        uses: actions/checkout@v2
        with:
          repository: bitsstdcheee/code-backup
          ref: development
          path: code-backup
            # token: ${{ secrets.status-token }}
          token: ${{ secrets.REPO_KEY }}
          fetch-depth: 1
      - name: 克隆仓库 (本仓库)
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: status
      - name: 编译 (Markdown)
        id: compile-markdown
        run: |
          g++ status/main.cpp -o status/main_markdown -DCI -DOUT_Markdown
      - name: 编译 (Out)
        id: compile-out
        run: |
          g++ status/main.cpp -o status/main_out -DCI
      - name: 运行 (Markdown)
        id: run-markdown
        if: always() && steps.compile-markdown.conclusion == 'success'
        run: |
          ./status/main_markdown > output.md
      - name: 运行 (Out)
        if: always() && steps.compile-out.conclusion == 'success'
        id: run-out
        run: |
          ./status/main_out > output.txt
      - name: 输出结果 (Markdown)
        if: always()
        run: |
          cat output.md
      - name: 输出结果 (Out)
        if: always()
        run: |
          cat output.txt
      - name: 上传构件 (code-backup)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-backup-repo
          path: |
            code-backup
            !code-backup/.git
      - name: 上传构件 (code-backup-status)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-backup-status-repo
          path: |
            status
            !status/.git
      - name: 上传构建 (output)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            output.md
            output.txt
