name: Runner
on:
  push:
  workflow_dispatch:
jobs:
  update_status:
    name: 更新代码状态
      # secrets:
      # status-token: ${{ github.REPO_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库 (bitsstdcheee/code-backup)
        uses: actions/checkout@v2
        with:
          repository: bitsstdcheee/code-backup
          ref: development
          path: code-backup
            # token: ${{ secrets.status-token }}
          token: ${{ secrets.REPO_KEY }}
          fetch-depth: 1
      - name: 克隆仓库 (本仓库)
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: status
      - name: 编译
        run: |
          g++ status/main.cpp -o status/main -DCI
      - name: 运行
        id: run
        run: |
          ./status/main > output.txt
      - name: 输出结果
        if: always()
        run: |
          cat output.txt
      - name: 上传构件 (code-backup)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-backup-repo
          path: |
            code-backup
            !code-backup/.git
      - name: 上传构件 (code-backup-status)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-backup-status-repo
          path: |
            status
            !status/.git
      - name: 上传构建 (output.txt)
        if: always() && steps.run.conclusion == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: output
